Rename official builds to "Google Chrome" on disk and "Chrome" in the menubar.
BUG=11826
Review URL: http://codereview.chromium.org/115474

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@16313 0039d316-1c4b-4281-b951-d872f2087c98

diff --git a/build/mac/build_app_dmg b/build/mac/build_app_dmg
--- a/build/mac/build_app_dmg
+++ b/build/mac/build_app_dmg
@@ -21,11 +21,20 @@ set -e
 TOP="${SRCROOT}/.."
 PKG_DMG="${TOP}/build/mac/pkg-dmg"
 
-APP_NAME=$1
+BUILD_BRANDING=$1
+if [ "${BUILD_BRANDING}" == "Chromium" ]; then
+  APP_NAME="Chromium"
+  DMG_NAME="Chromium.dmg"
+elif [ "${BUILD_BRANDING}" == "Chrome" ]; then
+  APP_NAME="Google Chrome"
+  DMG_NAME="GoogleChrome.dmg"
+else
+  echo "error: unknown branding: ${BUILD_BRANDING}" >&2
+  exit 1
+fi
+
 SRC_APP_PATH="${BUILT_PRODUCTS_DIR}/${APP_NAME}.app"
 VOL_NAME="${APP_NAME}"
-# Do we want a svn version in the DMG name?
-DMG_NAME="${APP_NAME}.dmg"
 DST_DMG_PATH="${BUILT_PRODUCTS_DIR}/${DMG_NAME}"
 
 # show things as we run them
diff --git a/build/mac/dump_app_syms b/build/mac/dump_app_syms
--- a/build/mac/dump_app_syms
+++ b/build/mac/dump_app_syms
@@ -19,10 +19,17 @@ fi
 
 TOP="${SRCROOT}/.."
 BUILD_BRANDING=$1
+if [ "${BUILD_BRANDING}" == "Chromium" ]; then
+  SRC_APP_NAME="Chromium"
+elif [ "${BUILD_BRANDING}" == "Chrome" ]; then
+  SRC_APP_NAME="Google Chrome"
+else
+  echo "error: unknown branding: ${BUILD_BRANDING}" >&2
+  exit 1
+fi
 
 . "${TOP}/chrome/VERSION"
 
-SRC_APP_NAME="${BUILD_BRANDING}"
 BREAKPAD_DUMP_SYMS="${BUILT_PRODUCTS_DIR}/dump_syms"
 BREAKPAD_PRODUCT_ID="${BUILD_BRANDING}_Mac"
 FULL_VERSION="${MAJOR}.${MINOR}.${BUILD}.${PATCH}"
diff --git a/build/mac/tweak_app_infoplist b/build/mac/tweak_app_infoplist
--- a/build/mac/tweak_app_infoplist
+++ b/build/mac/tweak_app_infoplist
@@ -54,7 +54,15 @@ fi
 
 TOP="${SRCROOT}/.."
 BUILD_BRANDING=$1
-SRC_APP_PATH="${BUILT_PRODUCTS_DIR}/${BUILD_BRANDING}.app"
+if [ "${BUILD_BRANDING}" == "Chromium" ]; then
+  APP_NAME="Chromium"
+elif [ "${BUILD_BRANDING}" == "Chrome" ]; then
+  APP_NAME="Google Chrome"
+else
+  echo "error: unknown branding: ${BUILD_BRANDING}" >&2
+  exit 1
+fi
+SRC_APP_PATH="${BUILT_PRODUCTS_DIR}/${APP_NAME}.app"
 
 set -x
 
@@ -85,7 +93,7 @@ COPYRIGHT_STRING=$(sed -n -e 's/^COPYRIGHT=\(.*\)$/\1/p' "${BRANDING_FILE}")
 COPYRIGHT_STRING=$(echo "${COPYRIGHT_STRING}" | sed -e $'s/([cC])/\302\251/g')
 
 # Build the full copyright string
-LONG_COPYRIGHT="${BUILD_BRANDING} ${FULL_VERSION}, ${COPYRIGHT_STRING}"
+LONG_COPYRIGHT="${APP_NAME} ${FULL_VERSION}, ${COPYRIGHT_STRING}"
 
 # I really hate how "defaults" doesn't take a real pathname but instead insists
 # on appending ".plist" to everything.
